using System.Diagnostics;
using System.Security.Cryptography.X509Certificates;
using Microsoft.Win32;

namespace FcDriverFixer.Core;

/// <summary>
/// Reads how Windows has bound a driver to a USB device, and reverts it via pnputil.
/// This is the basis of the "cannot make things worse" promise: we can always undo an
/// install, and repair the classic self-inflicted brick where someone ran Zadig on
/// their COM port and replaced the stock serial driver.
///
/// The registry chain we follow (verified on hardware):
///   Enum\USB\VID_xxxx&amp;PID_yyyy\&lt;instance&gt;    -> value "Driver" = "{classGuid}\NNNN"
///   Control\Class\{classGuid}\NNNN               -> value "InfPath" = "oemNN.inf"
/// Only third-party packages are named "oemNN.inf"; inbox drivers (e.g. usbser.inf) are
/// never oemNN and must never be deleted — we only ever remove OEM packages.
/// </summary>
public static class DriverStore
{
    public readonly record struct Binding(string InstanceId, string? Service, string? OemInf, string? Provider);

    /// <summary>All present bindings for a VID/PID (usually one).</summary>
    public static List<Binding> GetBindings(ushort vid, ushort pid)
    {
        var result = new List<Binding>();
        string vp = $"VID_{vid:X4}&PID_{pid:X4}";
        using RegistryKey? vpKey = Registry.LocalMachine.OpenSubKey(
            $@"SYSTEM\CurrentControlSet\Enum\USB\{vp}");
        if (vpKey is null) return result;

        foreach (string instance in vpKey.GetSubKeyNames())
        {
            using RegistryKey? inst = vpKey.OpenSubKey(instance);
            if (inst is null) continue;

            string instanceId = $@"USB\{vp}\{instance}";
            string? service = inst.GetValue("Service") as string;
            string? driver = inst.GetValue("Driver") as string;   // "{guid}\NNNN"
            string? oemInf = null, provider = null;

            if (!string.IsNullOrEmpty(driver))
            {
                using RegistryKey? cls = Registry.LocalMachine.OpenSubKey(
                    $@"SYSTEM\CurrentControlSet\Control\Class\{driver}");
                if (cls is not null)
                {
                    string? inf = cls.GetValue("InfPath") as string;
                    provider = cls.GetValue("ProviderName") as string;
                    if (inf is not null && inf.StartsWith("oem", StringComparison.OrdinalIgnoreCase))
                        oemInf = inf;   // only OEM packages are deletable
                }
            }
            result.Add(new Binding(instanceId, service, oemInf, provider));
        }
        return result;
    }

    /// <summary>Is this device bound to a removable OEM driver package (vs a Windows inbox one)?</summary>
    public static bool HasOemBinding(ushort vid, ushort pid) =>
        GetBindings(vid, pid).Exists(b => b.OemInf is not null);

    public readonly record struct PnpResult(int Code, string Output)
    {
        // pnputil: 0 = ok, 3010 = ok-but-reboot-recommended.
        public bool Ok => Code is 0 or 3010;
    }

    private static PnpResult RunPnputil(params string[] args)
    {
        var psi = new ProcessStartInfo("pnputil.exe")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        foreach (var a in args) psi.ArgumentList.Add(a);

        using var p = Process.Start(psi)!;
        string outText = p.StandardOutput.ReadToEnd() + p.StandardError.ReadToEnd();
        p.WaitForExit(30000);
        return new PnpResult(p.ExitCode, outText.Trim());
    }

    /// <summary>Delete an OEM driver package and unbind it from any device using it.</summary>
    public static PnpResult DeleteOemDriver(string oemInf) =>
        RunPnputil("/delete-driver", oemInf, "/uninstall", "/force");

    /// <summary>Force a re-enumeration so Windows re-selects a driver for now-unbound devices.</summary>
    public static PnpResult ScanDevices() => RunPnputil("/scan-devices");

    /// <summary>Remove a device node (it comes back on next scan/replug with a fresh driver pick).</summary>
    public static PnpResult RemoveDevice(string instanceId) =>
        RunPnputil("/remove-device", instanceId);

    /// <summary>
    /// Remove the self-signed "libwdi autogenerated" code-signing certificate for a VID/PID
    /// from the machine Root and TrustedPublisher stores. Part of a clean Undo: the install
    /// added it, so a full revert should take it back out. Requires elevation.
    /// The cert has no private key (libwdi deletes it after signing), so this is purely
    /// tidying the trust stores. Returns how many certs were removed.
    /// </summary>
    public static int RemoveLibwdiCert(ushort vid, ushort pid)
    {
        string idFragment = $"VID_{vid:X4}&PID_{pid:X4}";
        int removed = 0;
        foreach (var storeName in new[] { StoreName.Root, StoreName.TrustedPublisher })
        {
            try
            {
                using var store = new X509Store(storeName, StoreLocation.LocalMachine);
                store.Open(OpenFlags.ReadWrite);
                foreach (var cert in store.Certificates)
                {
                    if (cert.Subject.Contains(idFragment, StringComparison.OrdinalIgnoreCase) &&
                        cert.Subject.Contains("libwdi", StringComparison.OrdinalIgnoreCase))
                    {
                        store.Remove(cert);
                        removed++;
                    }
                }
            }
            catch
            {
                // Non-fatal: leaving a harmless (private-key-less) cert behind is acceptable.
            }
        }
        return removed;
    }
}
